### ISSUE TITLE
Strike as a initial bowl does not apply zero to 2nd bowl in first frame

### ISSUE THREAD

**Issue by dkouvdis** [matchilling/kata-js#1]
https://github.com/matchilling/kata-js/blob/cffed8c1f4159bd05d78eaf65eea7cff459097d1/src/bowling/index.js#L51-L52

FIrst two rolls
Game.roll(10)
Game.roll(2)
becomes `[10, 2]`
instead of `[10, 0]`

**Comment by matchilling** [comment]
Fixed it here [374041fabe08e14d98832d2dae3b9a653418786c](https://github.com/matchilling/kata-js/commit/374041fabe08e14d98832d2dae3b9a653418786c), thanks 😜
